---
title: "Research"
output: html_document
#date: "2024-10-20"
---

You can visit my [Google Scholar](https://scholar.google.com/citations?user=9pQjY1IAAAAJ&hl=en) profile.


#
#
#


## Published papers
--  [The Impact of Syrian Refugees on the Overeducation of Natives: Evidence from Turkish Labor Markets](overeducation.html) -- Accepted for publication at *The Journal of Development Studies*.

2025  [Shooting down trade: Firm-level effects of embargoes](sdown.html) -- with [Julian Hinz](https://julianhinz.com/) & [Cem Özgüzel](https://sites.google.com/view/cemozguzel/home), *Journal of Economic Behavior and Organization*, 231, 108621.


2021  [Global value chain integration and productivity: the case of Turkish manufacturing firms](gvc.html) -- with [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan)  & [Oytun Meçik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik), *Middle East Development Journal*, 13, 1, 150-171.


2021  [How far the apple falls from the tree: Intergenerational transmission of educational attainment in Indonesia](howfar.html) -- with [Syed Hassan Raza](http://www.qau.edu.pk/profile.php?id=809037), *International Journal of Educational Development*, 81, 10234.


#
#

#### in National Journals:
2026  [Robots, Employment and Wages: Evidence from Turkish Labor Markets](robot_121G176.html) -- with [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan), [Oytun Meçik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik) & [Ümit Yapıcı](https://unis.ahievran.edu.tr/akademisyen/umityapici), *World Journal of Applied Economics*, 52, 2, 265-288.

2025  [Exchange rate elasticity of exports and firm heterogeneity: Evidence from Turkish manufacturing firms](122R003.html) -- with [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan), [Oytun Meçik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik) & [Ünal Töngür](https://avesis.akdeniz.edu.tr/unaltongur/), *METU Studies in Development*, 52, 2, 265-288.

2023  [Wage Returns to Field of Study-Occupation Mismatch in Turkish Graduate Labor Market: Quantile Regression Approach](hmismatch.html) -- with [Oytun Mecik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik), *Ege Academic Review*, 23, 4, 653-666.

2018  [Industry Level Competitiveness and Adaptation to World Demand: An Analysis on Turkey and Selected Countries](esogu_demand.html) -- with [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan), *Eskişehir Osmangazi Üniversitesi İİBF Dergisi*, 13, 1, 143-166.

2018  [A Regional Approach to the Premature Deindustrialization in the Turkish
Economy](metu_denind.html) -- with [Oytun Mecik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik), *METU Studies in Development*, 45, 1, 59-81.


#
#
#

## Working papers

2026 [Even the Announcement Matters? The Effect of the Carbon Border Adjustment Mechanism on Exporter Behavior](cbam.html) -- with [Gunhild Berg](https://blogs.worldbank.org/en/team/g/gunhild-berg),  [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun) & [Etkin Özen](https://blogs.worldbank.org/en/team/e/etkin-ozen), *World Bank Policy Research Working Papers*.

2026 [Worker- and Firm-Level Effects of an Outsourcing Ban](outsourcing.html) with [Eren Gürer](https://sites.google.com/view/erengurer) & [Erol Taymaz](https://users.metu.edu.tr/etaymaz/), *CESifo Working Paper Series*. Revise and Resubmit at *Journal of Development Economics*.


2025 [Firm-level Effects of Minimum Wages](minwage_prices.html) -- with [Yusuf Emre Akgündüz](http://myweb.sabanciuniv.edu/emreakgunduz/), [Seyit Mümin Cılasun](https://avesis.tedu.edu.tr/seyit.cilasun) & [Murat G. Kırdar](https://muratguraykirdar.weebly.com/), *ERF Working Paper Series*.


2024  [The Impact of Minimum Wage Shock on Robot Adaption in Turkey](minwage_robot.html) -- with [Okan Akarsu](https://sites.google.com/view/okanakarsu/home), [Yusuf Emre Akgündüz](http://myweb.sabanciuniv.edu/emreakgunduz/) & [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun), *ERF Working Paper Series*.



#
#
#

## Work in progress

-- [Trade Liberalization and Firm-Level Prices](custom_union.html) with [Erol Taymaz](https://users.metu.edu.tr/etaymaz/) & [Kamil Yılmaz](https://sites.google.com/view/kamilyilmaz/).


-- [Firm-level Gravity with Fixed Effects](fes_firm.html) with [Julian Hinz](https://julianhinz.com/), [Cem Özgüzel](https://sites.google.com/view/cemozguzel/home) & [Joschka Wanner](https://www.ifw-kiel.de/experts/joschka-wanner/).


-- Environmental taxation and Carbon Leakage -- with [Sinem Ayhan](https://www.iza.org/person/8759/sinem-h-ayhan),  [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun) & [Johannes Galle](https://ipc.sabanciuniv.edu/en/johannes-galle-a4ec02).




<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-117RN0RJWP"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-117RN0RJWP');
</script>