---
title: "CV"
output: html_document
#date: "2024-10-20"
---


  
  
##
  
  Click  [here](https://drive.google.com/file/d/12PedDMmyBygtcXc69DUDty8EZyiUGElg/view?usp=sharing) to see my Vita in PDF.
  

#
#
#
#
#
#

## Education

2010-2017 Ph.D, Economics, [Anadolu University](https://anadolu.edu.tr/en) (Advisor: [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan))

\ \ \ \ \ \ \ Thesis title: *Competitiveness and Complexity in the Manufacturing Industries:* 

\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  *A Cross-country Analysis* (in Turkish)

2004-2008 B.Sc, Economics, [Anadolu University](https://anadolu.edu.tr/en)


#
#
#
#
#
#



## Experience
2024-2025 Short-term consultant, [World Bank](https://www.worldbank.org/ext/en/home)

2024-2025 Postdoctoral Researcher, [Department of Economics](https://econ.metu.edu.tr/en), [METU](https://www.metu.edu.tr/), (Advisor: [Erol Taymaz](https://users.metu.edu.tr/etaymaz/) & [Kamil Yılmaz](https://sites.google.com/view/kamilyilmaz/))

2020- Assistant Professor, Department of Economics, [Dumlupınar University](https://dpu.edu.tr/en)

2010-17 Department of Economics, [Anadolu University](https://anadolu.edu.tr/en)

2016-2017 Project Trainee, [CEPII](http://www.cepii.fr/CEPII/en/welcome.asp)

2014 Visiting Researcher, [Department of Economics](https://www.csusb.edu/economics), [California State University, San Bernardino](https://www.csusb.edu/)

#
#
#
#
#
#

## Awards & honors
2025 Best Paper Award by [Economic Research Forum (ERF)](https://erf.org.eg)

2022-2024 TUBITAK Project Grant, *Robots, Employment and wages* (Project Number: 121G176, Role: PI)

2022-2024 TUBITAK Project Grant, *Elasticity of Turkish Export Outcomes to the Exchange Rates: Product and Firm Level Analysis* (Project Number: 122R003, Role: PI)

2021 [Ibn Khaldun Best Paper](https://meeaweb.org/ibn-khaldun-winners) Award by [Middle East Economic Association (MEEA)](https://meeaweb.org/)

2008 High Honor Student at the [Anadolu University](https://anadolu.edu.tr/en)

#
#
#
#
#
#

## Journal articles
2025  [Shooting down trade: Firm-level effects of embargoes](sdown.html) -- with [Julian Hinz](https://julianhinz.com/) & [Cem Özgüzel](https://sites.google.com/view/cemozguzel/home), [*Journal of Economic Behavior and Organization*](https://www.sciencedirect.com/journal/journal-of-economic-behavior-and-organization), 231, 108621.

2023  [Wage Returns to Field of Study-Occupation Mismatch in Turkish Graduate Labor Market: Quantile Regression Approach](hmismatch.html) -- with [Oytun Mecik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik), [*Ege Academic Review*](https://dergipark.org.tr/en/pub/eab), 23, 4, 653-666.


2021  [Global value chain integration and productivity: the case of Turkish manufacturing firms](gvc.html) -- with [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan)  & [Oytun Meçik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik), [*Middle East Development Journal*](https://www.tandfonline.com/journals/rmdj20), 13, 1, 150-171.


2021  [How far the apple falls from the tree: Intergenerational transmission of educational attainment in Indonesia](howfar.html) -- with [Syed Hassan Raza](http://www.qau.edu.pk/profile.php?id=809037), [*International Journal of Educational Development*](https://www.sciencedirect.com/journal/international-journal-of-educational-development), 13, 1, 150-171.


#
#

#### In Turkish:
2025  [Exchange rate elasticity of exports and firm heterogeneity: Evidence from Turkish manufacturing firms](122R003.html) -- with [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan), [Oytun Meçik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik) & [Ünal Töngür](https://avesis.akdeniz.edu.tr/unaltongur/).
forthcoming in [*METU Studies in Development*](http://www2.feas.metu.edu.tr/metusd/ojs/index.php/metusd/index).

2018  [Industry Level Competitiveness and Adaptation to World Demand: An Analysis on Turkey and Selected Countries](esogu_demand.html) -- with [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan), [*Eskişehir Osmangazi Üniversitesi İİBF Dergisi*](https://dergipark.org.tr/tr/pub/oguiibf), 13, 1, 143-166.

2018  [A Regional Approach to the Premature Deindustrialization in the Turkish
Economy](metu_denind.html) -- with [Oytun Mecik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik), [*METU Studies in Development*](http://www2.feas.metu.edu.tr/metusd/ojs/index.php/metusd/index), 45, 1, 59-81.


#
#
#

## Working papers
2025 [Firm-level Effects of Minimum Wages](minwage_prices.html) -- with [Yusuf Emre Akgündüz](http://myweb.sabanciuniv.edu/emreakgunduz/), [Seyit Mümin Cılasun](https://avesis.tedu.edu.tr/seyit.cilasun) & [Murat G. Kırdar](https://muratguraykirdar.weebly.com/), [*ERF Working Paper Series*](https://erf.org.eg/publication_cat/working-paper-series/).


2024  [The Impact of Minimum Wage Shock on Robot Adaption in Turkey](minwage_robot.html) -- with [Yusuf Emre Akgündüz](http://myweb.sabanciuniv.edu/emreakgunduz/) & [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun), [*ERF Working Paper Series*](https://erf.org.eg/publication_cat/working-paper-series/).

2023  [Robots, Employment and Wages: Evidence from Turkish Labor Markets](robot_121G176.html) -- with [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan), [Oytun Mecik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik) & [Ümit Yapıcı](https://unis.ahievran.edu.tr/akademisyen/umityapici), [*ERF Working Paper Series*](https://erf.org.eg/publication_cat/working-paper-series/).


2023  [The Impact of Syrian Refugees on the Overeducation of Natives: Evidence from Turkish Labor Markets](overeducation.html) -- with [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun), [*ERF Working Paper Series*](https://erf.org.eg/publication_cat/working-paper-series/).

#
#
#

## Work in progress

-- [Firm-level Effects of Minimum Wages](minwage_prices.html) -- with [Yusuf Emre Akgündüz](http://myweb.sabanciuniv.edu/emreakgunduz/) & [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun)

-- Firm Level Effects of Custom Union with [Erol Taymaz](https://users.metu.edu.tr/etaymaz/) & [Kamil Yılmaz](https://sites.google.com/view/kamilyilmaz/)


-- [Firm-level Gravity with Fixed Effects](fes_firm.html) with [Julian Hinz](https://julianhinz.com/), [Cem Özgüzel](https://sites.google.com/view/cemozguzel/home) & [Joschka Wanner](https://www.ifw-kiel.de/experts/joschka-wanner/)


-- Market Power, Firm Productivity, and Worker Efficiency -- with [Ufuk Akcigit](https://www.ufukakcigit.com/), [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun) & [Furkan Kilic](https://economics.uchicago.edu/directory/Furkan-K%C4%B1l%C4%B1c)

-- [Even the announcement matters? The effect of CBAM on exports and exporters](cbam.html) -- with [Gunhild Berg](https://blogs.worldbank.org/en/team/g/gunhild-berg),  [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun) & [Etkin Özen](https://blogs.worldbank.org/en/team/e/etkin-ozen)


-- Environmental taxation and Carbon Leakage -- with [Sinem Ayhan](https://www.iza.org/person/8759/sinem-h-ayhan),  [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun) & [Johannes Galle](https://ipc.sabanciuniv.edu/en/johannes-galle-a4ec02)

-- Minimum Wages and Within-Firm Wage Dispersion with [Seyit Mümin Cilasun](https://avesis.tedu.edu.tr/seyit.cilasun) and [Gonul Sengonul](https://www.ozyegin.edu.tr/en/faculty/gonulsengul).

#
#
#

## Referee

[*Review of World Economics*](https://link.springer.com/journal/10290), [*International Economics*](https://www.sciencedirect.com/journal/international-economics), [*International Migration*](https://onlinelibrary.wiley.com/journal/14682435), [*Applied Economics*](https://www.tandfonline.com/journals/raec20), [*The European Journal on Criminal Policy and Research*](https://link.springer.com/journal/10610)

#
#
#

## Skills

R, Stata, LaTeX


