---
  title: "Wage Returns to Field of Study-Occupation Mismatch in Turkish Graduate Labor Market: Quantile Regression Approach"
  output: html_document
#date: "2024-10-20"
---

  
## 
  with [Oytun Mecik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik), *Ege Academic Review*, 23, 4, 653-666. 

In this paper we estimate the income effects of horizontal mismatch and its interaction with fields of study for Turkish higher education graduates using Turkish Labor Force Survey dataset. After controlling the vertical mismatch to reduce potential bias, our baseline findings show that one point (decrease) increase in (mis)matching index leads to 21.9% wage (penalty) growth. However, the return to the matching varies significantly between fields of study. We also explore extent to which impact of horizontal mismatch is sensitive to the ability levels represented by conditional quantile of the income distribution of graduates. Our quantile regression estimations point us heterogenous matching returns for different quantiles of fields of study. While positive wage effect of matching is significantly valid at the above and below the median income in six and three majors respectively, three majors’ negative matching is at above the median income.

[Link to the paper](https://dergipark.org.tr/en/pub/eab/issue/80426/1164097)

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-117RN0RJWP"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-117RN0RJWP');
</script>