---
title: "Robots, Employment and Wages: Evidence from Turkish Labor Markets"
output: html_document
#date: "2024-10-20"
---


## 
with [Yılmaz Kılıçaslan](https://avesis.anadolu.edu.tr/ykilicaslan), [Oytun Mecik](https://iibf.ogu.edu.tr/Personel/Detay/14/doc-dr-oytun-mecik) and [Ümit Yapıcı](https://unis.ahievran.edu.tr/akademisyen/umityapici). Mimeo, June 2024.
Submitted to [*Journal of Knowledge Economy*](https://link.springer.com/journal/13132).

In recent years, effects of automation on labor market were outpaced due to the widespread usage of robots in various industries. However, empirical studies mostly cover developed countries. Our aim in this study is to investigate how the robotization in Turkey affects local and worker level labor market outcomes in Turkey. Using novel employer-employee data and Federation of Robotics (IFR) database for 2014-2021 period, we find in our baseline specification that unlike the existing literature, robot exposure has positive effects on employment growth of districts. These effects hold for manufacturing and nonmanufacturing industries separately, arguing that instead of crowding out of labor, reallocation between main industries -especially for younger aged workers- occurs. Moreover, we see this positive employment effect due to the robotization in automotive industry. Finally, worker level analysis reveals that incumbent workers in manufacturing industry have reduced their employment when they face robot exposure. Moreover, they were likely to separate their original workplace and occupation and unlikely to find another job in nonmanufacturing industry. However, if they manage to find a job, their earnings are found to be significantly higher than their initial job.

[Presentation slides](https://betam.bahcesehir.edu.tr/wp-content/uploads/2023/08/Robots-Employment-and-Wages-Evidence-from-Turkish-Labor-Market-1.pdf)

[ERF Working paper](https://erf.org.eg/publications/robots-employment-and-wages-evidence-from-turkish-labor-markets-2/?tab=undefined&c=undefined)
