---
#  title: "Ugur Aytun"
output: html_document
#date: "2024-10-20"
---


#
#
#
#
#
#

## Shooting down trade: Firm-level effects of embargoes
with [Julian Hinz](https://julianhinz.com/) and [Cem Özgüzel](https://sites.google.com/view/cemozguzel/home) Mimeo, April 2024, Revise and Resubmit at [Journal of Economic Behavior and Organization](https://www.sciencedirect.com/journal/journal-of-economic-behavior-and-organization).

In November 2015, Turkey unexpectedly downed a Russian military jet in Syria. Russia retaliated by imposing a sudden and complete embargo on certain Turkish exports effective within a month. We exploit this quasi-natural experiment to estimate the supply side effects of imposing and lifting the sanctions. Using administrative data covering all Turkish exporters, we first document the trade effects on the intensive margin of firms. We consider the direct embargo impact, diversion effects to other destinations, and circumvention effects towards other products. Second, we investigate the broader consequences of sanctions on firms' domestic sales, purchases, and employment, uncovering significant and lasting impacts beyond trade outcomes. We find that firms are affected temporarily — shifting trade and adjusting domestic sales, purchases and employment — but do not suffer long-lasting effects after the lifting of the embargo.


[METU-ERC Working paper](https://erc.metu.edu.tr/en/system/files/menu/series24/2404.pdf)

[Online appendix](https://uguraytun.github.io/uguraytun/shooting_down_trade_online_app.pdf)

[Presentation slides](https://julianhinz.com/research/shooting_down_trade/shooting_down_trade-slides.pdf)